### ISSUE TITLE
Use cargo-lambda for compilation

### ISSUE THREAD

**Issue by calavera** [rnag/rust.aws-cdk-lambda#5]
Hi 👋 

This is a really cool project, thanks for putting it together!

I wanted to let you know about this other project I started a few weeks ago and we recommend for people using the Rust runtime for Lambda:

https://github.com/calavera/cargo-lambda

It abstracts away cargo-zigbuild, and also installs Zig for people automatically. It would allow you to reduce the code necessary to compile and locate functions significantly. Check it out and let me what you think about it. I can also help you integrate it if you're interested.

**Comment by rnag** [comment]
These changes should now be published as version [v1.1.3](https://www.npmjs.com/package/rust.aws-cdk-lambda/v/1.1.3). @calavera thanks again for putting this together!
